### ISSUE TITLE
its literly just a inspect element

### ISSUE THREAD

**Issue by memer6942** [adaaamx2/robuxfree2022#2]
i didn't download or use this script but i looked at the script and it doesn't give any it just makes it look like it works its much easyer to use inspect element

**Comment by adaaamx2** [comment]
yes bro it doesnt, sorry i didnt mean to put it public

**Comment by memer6942** [comment]
makes sense lol

**Comment by memer6942** [comment]
idk why but it's fun just to inspect element and troll your friends lol

**Comment by adaaamx2** [comment]
have a good day my friend
